device: 'cuda:0'

dataloaders:
    _target_: net_complexity.dataloaders.ClassicCVDataloaders
    path_to_data: /home/machenike/IAD/sample_complexity_of_feature_selection_in_deep_tabular_models/data
    train_val_ratio: [0.8, 0.2]
    batch_size: 512
    taskname: MNIST
    
model:
  _target_: net_complexity.wrappers.ClassificationFeatureSelectionWrapper
  backbone:
    _target_: net_complexity.wrappers.ResNet50
    num_classes: 10
    in_channels: 3
    resnet_block: 
     _target_: net_complexity.wrappers.AIGBottleneckLayer
     _partial_: True
  lambda_coef: 0.05
  criterion: 
    _target_: torch.nn.CrossEntropyLoss
  regularization_loss:
    _target_: net_complexity.wrappers.get_AIG_regularization_loss
    _partial_: True

training_arguments:
  num_epochs: 25

metrics:
  _target_: net_complexity.meta.Metrics
  train_metrics:
    - _target_: net_complexity.metrics.base.MultiLossMetric
    - _target_: net_complexity.metrics.classification.Accuracy
    - _target_: net_complexity.metrics.aig.AIGActivationsMetric
  valid_metrics:
    - _target_: net_complexity.metrics.base.MultiLossMetric
    - _target_: net_complexity.metrics.classification.Accuracy
    - _target_: net_complexity.metrics.aig.AIGActivationsMetric
    
optimizer:
  _target_: torch.optim.AdamW
  lr: 0.01
  #_partial_: True

mlflow:
  tracking_uri: null  # or set to your MLflow server URI, e.g., "http://localhost:5000"
  experiment_name: "feature_selection_experiment"
  run_name: debug  # will auto-generate if not set
  log_model: true
  log_artifacts: true
  artifacts_dir: "./mlruns"
  tags:
    project: "net_complexity"
    model_type: "ResNet50_AIG"