# @package _global_

metrics:
  _target_: net_complexity.meta.Metrics
  train_metrics:
    - _target_: net_complexity.metrics.base.MultiLossMetric
    - _target_: net_complexity.metrics.classification.Accuracy
    - _target_: net_complexity.metrics.gumbel.GumbelProbMetric
  valid_metrics:
    - _target_: net_complexity.metrics.base.MultiLossMetric
    - _target_: net_complexity.metrics.classification.Accuracy
    - _target_: net_complexity.metrics.gumbel.GumbelProbMetric
  test_metrics:
    - _target_: net_complexity.metrics.complexity.ComputeCostMetric
    - _target_: net_complexity.metrics.base.MultiLossMetric
    - _target_: net_complexity.metrics.classification.Accuracy
    - _target_: net_complexity.metrics.gumbel.GumbelProbMetric
