# @package _global_

model:
  _target_: net_complexity.wrappers.AIGEfficientNetV2S
  num_classes: 10
  in_channels: 3
  lambda_coef: 0.000001
  bypass_on_zero_lambda: false
  dropout: 0.1
  stochastic_depth: 0.0
  gate_hidden_channels: 16
  keep_prob_init: 0.9
  gate_threshold: 0.5
  gate_temperature: 1.0
  gate_regularization: l2_gate
  # disabled | plus_negative_entropy | minus_negative_entropy
  entropy_regularization: disabled
  stem_stride: 1
  criterion:
    _target_: torch.nn.CrossEntropyLoss
