# @package _global_

model:
  _target_: net_complexity.wrappers.ClassificationFeatureSelectionWrapper
  backbone:
    _target_: net_complexity.wrappers.ResNet152
    num_classes: 200
    in_channels: 3
    stem_kernel_size: 3
    stem_stride: 1
    stem_padding: 1
    use_maxpool: false
