# @package _global_

model:
  bypass_on_zero_lambda: false
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  regularization_loss:
    _target_: net_complexity.wrappers.AIGRegularizationLoss
    norm: l2
  backbone:
    resnet_block:
      _target_: net_complexity.wrappers.AIGBottleneckLayer
      _partial_: true
      gate_regularization: l2_gate
