# @package _global_

model:
  bypass_on_zero_lambda: false
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  regularization_loss:
    _target_: net_complexity.wrappers.get_AIG_regularization_loss
    _partial_: true
  backbone:
    resnet_block:
      _target_: net_complexity.wrappers.AIGBottleneckLayer
      _partial_: true
