# @package _global_

model:
  gumbel_init_mode: auto
  bypass_on_zero_lambda: true
  criterion:
    _target_: torch.nn.CrossEntropyLoss
  regularization_loss:
    _target_: net_complexity.wrappers.get_gumbel_loss
    _partial_: true
  backbone:
    resnet_block:
      _target_: net_complexity.wrappers.CIFARGumbelBasicBlock
      _partial_: true
      force_ones_mask: false
      deterministic_soft_mask: false
      deterministic_hard_mask: false
