# @package _global_
# 4 * 15 search + 3 * 15 intermediate recovery + 45 final recovery = 150.

cyclic_channel_pruning:
  max_cycles: 4
  stop_on_convergence: false
  gumbel_epochs: 15
  recovery_epochs: 15
  final_epochs: 45
