defaults:
  - experiment: autopruner_mobilenetv2_tinyimagenet200_45ep
  - tuning: none
  - _self_

model:
  pretrained_checkpoint: ${hydra:runtime.cwd}/outputs/runs/20261002_194727_baseline_pretrained_mobilenetv2_tinyimagenet200/checkpoints/best.pt

mlflow:
  run_name: autopruner_mobilenetv2_tinyimagenet200_pilot_15_30_keep_05
  tags:
    recipe: autopruner_mobilenetv2_tinyimagenet200_pilot_15_30
    target_keep_ratio: "0.5"
    pruning_epochs: "15"
    fine_tune_epochs: "30"

hydra:
  run:
    dir: ${run_history.root_dir}/${now:%Y%m%d_%H%M%S}_${mlflow.run_name}
  output_subdir: .hydra
